# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

JTT_score <- function(q, m, E, Xy_, yPy, M_, D0, alp) {
    .Call('_JTT_JTT_score', PACKAGE = 'JTT', q, m, E, Xy_, yPy, M_, D0, alp)
}

